# Generated by Django 5.2.10 on 2026-01-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_match', 'New Match'), ('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('connection_declined', 'Connection Declined'), ('session_invite', 'Session Invite'), ('session_update', 'Session Update'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('friend_trip_posted', 'Friend Posted a Trip'), ('trip_overlap_detected', 'Trip Overlap Detected'), ('friend_in_home_crag', 'Friend Coming to Your Home Crag'), ('group_invite', 'Group Invitation'), ('group_trip_posted', 'Group Trip Posted'), ('group_trip_updated', 'Group Trip Updated')], max_length=50),
        ),
    ]
