# Generated by Django 5.2.10 on 2026-01-16 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_sessions', '0002_initial'),
        ('trips', '0005_trip_invited_users_trip_is_group_trip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='sessions_status_2c94db_idx'),
        ),
    ]
