# Generated by Django 5.2.10 on 2026-01-16 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('following', 'Following')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('connection_source', models.CharField(blank=True, choices=[('matched_trip', 'Met via Trip Match'), ('completed_session', 'Climbed Together'), ('manual_add', 'Manual Add'), ('imported', 'Imported from Contact')], max_length=50, null=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friendships',
                'indexes': [models.Index(fields=['requester', 'status'], name='friendships_request_74cfa7_idx'), models.Index(fields=['addressee', 'status'], name='friendships_address_4da91f_idx')],
                'unique_together': {('requester', 'addressee')},
            },
        ),
    ]
