# Generated by Django 5.0.1 on 2026-01-13 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_block', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('full_day', 'Full Day'), ('rest', 'Rest Day')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'availability_blocks',
                'ordering': ['date', 'time_block'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('primary_disciplines', models.JSONField(default=list, help_text="['sport', 'trad']")),
                ('season', models.CharField(blank=True, help_text="Best season (e.g., 'Oct-May')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'destinations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('disciplines', models.JSONField(default=list, help_text="['sport']")),
                ('approach_time', models.IntegerField(blank=True, help_text='Minutes from parking', null=True)),
                ('route_count', models.IntegerField(blank=True, help_text='Approximate route count', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crags', to='trips.destination')),
            ],
            options={
                'db_table': 'crags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_crag_notes', models.CharField(blank=True, help_text='If specific crag not in database', max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('preferred_disciplines', models.JSONField(default=list, help_text="['sport', 'bouldering']")),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trips.destination')),
                ('preferred_crags', models.ManyToManyField(blank=True, related_name='trips', to='trips.crag')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['start_date'],
            },
        ),
    ]
