# Generated by Django 5.0.1 on 2026-01-13 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availabilityblock',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='trips.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='crag',
            unique_together={('destination', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='trip_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityblock',
            unique_together={('trip', 'date', 'time_block')},
        ),
    ]
