# Generated by Django 5.2.10 on 2026-01-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        # Add Mountain Project fields to Destination model
        migrations.AddField(
            model_name='destination',
            name='mp_id',
            field=models.CharField(max_length=50, blank=True, null=True, unique=True, help_text='Mountain Project area ID'),
        ),
        migrations.AddField(
            model_name='destination',
            name='mp_url',
            field=models.URLField(blank=True, help_text='Mountain Project area URL'),
        ),
        migrations.AddField(
            model_name='destination',
            name='mp_star_rating',
            field=models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True, help_text='Mountain Project star rating (0-4)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='mp_star_votes',
            field=models.IntegerField(null=True, blank=True, help_text='Number of star rating votes'),
        ),
        migrations.AddField(
            model_name='destination',
            name='location_hierarchy',
            field=models.JSONField(default=list, help_text='Location hierarchy from MP (e.g., ["USA", "Kentucky", "Red River Gorge"])'),
        ),
        migrations.AddField(
            model_name='destination',
            name='last_synced',
            field=models.DateTimeField(null=True, blank=True, help_text='Last time data was synced from Mountain Project'),
        ),

        # Add Mountain Project fields to Crag model
        migrations.AddField(
            model_name='crag',
            name='mp_id',
            field=models.CharField(max_length=50, blank=True, null=True, unique=True, help_text='Mountain Project area/crag ID'),
        ),
        migrations.AddField(
            model_name='crag',
            name='mp_url',
            field=models.URLField(blank=True, help_text='Mountain Project URL'),
        ),
        migrations.AddField(
            model_name='crag',
            name='mp_star_rating',
            field=models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True, help_text='Mountain Project star rating (0-4)'),
        ),
        migrations.AddField(
            model_name='crag',
            name='parent_area_mp_id',
            field=models.CharField(max_length=50, blank=True, null=True, help_text='Mountain Project ID of parent area'),
        ),
        migrations.AddField(
            model_name='crag',
            name='last_synced',
            field=models.DateTimeField(null=True, blank=True, help_text='Last time data was synced from Mountain Project'),
        ),

        # Add indexes for better query performance
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['mp_star_rating'], name='destinations_mp_star_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['country'], name='destinations_country_idx'),
        ),
    ]
