# Generated by Django 5.2.10 on 2026-01-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_add_mountain_project_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='destination',
            name='destinations_mp_star_idx',
        ),
        migrations.RemoveIndex(
            model_name='destination',
            name='destinations_country_idx',
        ),
        migrations.AddField(
            model_name='trip',
            name='grade_system',
            field=models.CharField(blank=True, help_text='Grade system used (yds, french, v_scale)', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='max_grade',
            field=models.CharField(blank=True, help_text="Maximum grade for this trip (e.g., '5.12c', 'V8', '7b')", max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='min_grade',
            field=models.CharField(blank=True, help_text="Minimum grade for this trip (e.g., '5.10a', 'V4', '6b')", max_length=10),
        ),
    ]
