# Generated by Django 5.2.10 on 2026-01-16 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_destination_destinations_mp_star_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_group_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='notes_private',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='notes_public',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='visibility_status',
            field=models.CharField(choices=[('looking_for_partners', 'Looking for Partners'), ('open_to_friends', 'Open to Friends'), ('full_private', 'Full/Private')], default='open_to_friends', max_length=20),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['start_date', 'end_date'], name='trips_start_d_518e71_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'is_active', 'start_date'], name='trips_user_id_7e6b88_idx'),
        ),
    ]
