from django.db import models
from django.conf import settings
import uuid


class TripOverlap(models.Model):
    """
    Represents a detected overlap between two users' trips.
    Auto-generated by the Overlap Engine.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    user1 = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='overlaps_as_user1'
    )
    user2 = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='overlaps_as_user2'
    )

    trip1 = models.ForeignKey(
        'trips.Trip',
        on_delete=models.CASCADE,
        related_name='overlaps_as_trip1'
    )
    trip2 = models.ForeignKey(
        'trips.Trip',
        on_delete=models.CASCADE,
        related_name='overlaps_as_trip2'
    )

    # Overlap details
    overlap_destination = models.ForeignKey(
        'trips.Destination',
        on_delete=models.CASCADE
    )
    overlap_start_date = models.DateField()
    overlap_end_date = models.DateField()
    overlap_days = models.IntegerField()  # Number of overlapping days

    # Overlap score (0-100) based on:
    # - Number of overlapping days
    # - Discipline compatibility
    # - Friendship status
    # - Distance from user's home crag
    overlap_score = models.IntegerField()

    # Notification tracking
    notification_sent = models.BooleanField(default=False)
    notification_sent_at = models.DateTimeField(null=True, blank=True)

    # User actions
    user1_dismissed = models.BooleanField(default=False)
    user2_dismissed = models.BooleanField(default=False)
    connection_created = models.BooleanField(default=False)  # Did they connect?

    detected_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'trip_overlaps'
        unique_together = ('trip1', 'trip2')
        indexes = [
            models.Index(fields=['overlap_start_date', 'notification_sent']),
            models.Index(fields=['user1', 'notification_sent']),
            models.Index(fields=['user2', 'notification_sent']),
        ]

    def __str__(self):
        return f"Overlap: {self.user1} & {self.user2} at {self.overlap_destination} ({self.overlap_days} days)"