# Generated by Django 5.2.10 on 2026-01-16 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0005_trip_invited_users_trip_is_group_trip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripOverlap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overlap_start_date', models.DateField()),
                ('overlap_end_date', models.DateField()),
                ('overlap_days', models.IntegerField()),
                ('overlap_score', models.IntegerField()),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user1_dismissed', models.BooleanField(default=False)),
                ('user2_dismissed', models.BooleanField(default=False)),
                ('connection_created', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('overlap_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.destination')),
                ('trip1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlaps_as_trip1', to='trips.trip')),
                ('trip2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlaps_as_trip2', to='trips.trip')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlaps_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlaps_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trip_overlaps',
                'indexes': [models.Index(fields=['overlap_start_date', 'notification_sent'], name='trip_overla_overlap_5e9acc_idx'), models.Index(fields=['user1', 'notification_sent'], name='trip_overla_user1_i_d2cc45_idx'), models.Index(fields=['user2', 'notification_sent'], name='trip_overla_user2_i_51148a_idx')],
                'unique_together': {('trip1', 'trip2')},
            },
        ),
    ]
