# Generated by Django 5.0.1 on 2026-01-13 11:05

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceTag',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('skill', 'Skill'), ('equipment', 'Equipment'), ('logistics', 'Logistics'), ('preference', 'Preference')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'experience_tags',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Behavior'), ('spam', 'Spam'), ('safety', 'Safety Concern'), ('fake', 'Fake Profile'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserExperienceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_experience_tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('home_location', models.CharField(help_text='City, Country', max_length=200)),
                ('home_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('home_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive')], default='balanced', max_length=20)),
                ('preferred_grade_system', models.CharField(choices=[('yds', 'YDS'), ('french', 'French'), ('v_scale', 'V-Scale')], default='yds', max_length=10)),
                ('profile_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='DisciplineProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discipline', models.CharField(choices=[('sport', 'Sport Climbing'), ('trad', 'Trad Climbing'), ('bouldering', 'Bouldering'), ('multipitch', 'Multipitch'), ('gym', 'Gym Climbing')], max_length=20)),
                ('grade_system', models.CharField(choices=[('yds', 'YDS'), ('french', 'French'), ('v_scale', 'V-Scale')], max_length=10)),
                ('comfortable_grade_min_display', models.CharField(help_text="User-entered grade (e.g., '5.10a')", max_length=10)),
                ('comfortable_grade_max_display', models.CharField(help_text="User-entered grade (e.g., '5.11c')", max_length=10)),
                ('projecting_grade_display', models.CharField(blank=True, help_text='Optional projecting grade', max_length=10)),
                ('comfortable_grade_min_score', models.IntegerField()),
                ('comfortable_grade_max_score', models.IntegerField()),
                ('projecting_grade_score', models.IntegerField(blank=True, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('can_lead', models.BooleanField(default=False)),
                ('can_belay', models.BooleanField(default=True)),
                ('can_build_anchors', models.BooleanField(default=False, help_text='For trad/multipitch')),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discipline_profiles',
            },
        ),
        migrations.CreateModel(
            name='GradeConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('sport', 'Sport Climbing'), ('trad', 'Trad Climbing'), ('bouldering', 'Bouldering'), ('multipitch', 'Multipitch'), ('gym', 'Gym Climbing')], max_length=20)),
                ('score', models.IntegerField()),
                ('yds_grade', models.CharField(blank=True, help_text="e.g., '5.10a'", max_length=10)),
                ('french_grade', models.CharField(blank=True, help_text="e.g., '6a'", max_length=10)),
                ('v_scale_grade', models.CharField(blank=True, help_text="e.g., 'V3'", max_length=10)),
            ],
            options={
                'db_table': 'grade_conversions',
                'ordering': ['discipline', 'score'],
                'indexes': [models.Index(fields=['discipline', 'yds_grade'], name='grade_conve_discipl_40b315_idx'), models.Index(fields=['discipline', 'french_grade'], name='grade_conve_discipl_c88ee3_idx'), models.Index(fields=['discipline', 'v_scale_grade'], name='grade_conve_discipl_a57dae_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='gradeconversion',
            constraint=models.UniqueConstraint(fields=('discipline', 'score'), name='unique_grade_per_discipline'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userexperiencetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.experiencetag'),
        ),
        migrations.AddField(
            model_name='userexperiencetag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.CheckConstraint(check=models.Q(('blocker', models.F('blocked')), _negated=True), name='block_no_self_block'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AlterUniqueTogether(
            name='disciplineprofile',
            unique_together={('user', 'discipline')},
        ),
        migrations.AlterUniqueTogether(
            name='userexperiencetag',
            unique_together={('user', 'tag')},
        ),
    ]
