# Generated by Django 5.2.10 on 2026-01-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Your gender identity (optional)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_partner_gender',
            field=models.CharField(choices=[('no_preference', 'No preference'), ('prefer_male', 'Prefer male'), ('prefer_female', 'Prefer female'), ('prefer_non_binary', 'Prefer non-binary'), ('same_gender', 'Same gender as me')], default='no_preference', help_text='Gender preference for climbing partners', max_length=20),
        ),
    ]
