# Generated by Django 5.2.10 on 2026-01-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender_user_preferred_partner_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_weight_difference',
            field=models.CharField(choices=[('no_preference', 'No preference'), ('similar', 'Similar weight (± 15kg / 33lbs)'), ('moderate', 'Moderate difference (± 30kg / 66lbs)'), ('close', 'Close weight (± 10kg / 22lbs)')], default='no_preference', help_text='Acceptable weight difference for safe belaying', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.IntegerField(blank=True, help_text='Your weight in kilograms (for belay safety matching)', null=True),
        ),
    ]
