# Generated by Django 5.2.10 on 2026-01-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_user_preferred_weight_difference_user_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker'], name='blocks_blocker_42b25f_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocked'], name='blocks_blocked_0ecc50_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verified', 'profile_visible'], name='users_email_v_74a57d_idx'),
        ),
    ]
